#!/usr/bin/env bash
#  Bash (init) script that manages `manage_my_process` with start/stop/restart argumener/run/my_process.pid"

if [ "${1}" == "start" ]
then
  ./manage_my_process &
  touch /var/run/my_process.pid
  echo $1 > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ] then
  kill "$(pgrep /manage_my_process)" 
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$1" == "restart" ] then
  kill "$(pgrep -f /manage_my_process)"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo $1 > /var/run/my_process.pid
  touch /var/run/my_process.pid
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
