#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
# Show all processes, for all users
# Including those which might not have a TTY
# Display in a user-oriented format

ps -auxf
