#!/usr/bin/env bash
# Script that displays the content of the file '/etc/passwd'.
# Display username, user id, home directory path for the user

passwd="/etc/passwd"

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "$passwd"
