#!/usr/bin/env bash
# Script that displays the content of the file '/etc/passwd'.
# Display username, user id, home directory path for the user

while read passwd
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
