#!/usr/bin/env bash
# Script that displays the content of the file '/etc/passwd'.
# Display username
# Display user id
# Display home directory path for the user

while read passwd
do
	echo "$passwd" | cut -d ":" -f1,3,6
done < "$FILE"
