#!/usr/bin/env bash
# Script that displays 'Best School' 10 times but for the 9th iteration, displays 'Best School' and then 'Hi' on a new line.

i=0

while (( "$i" < 10 ))
do
	echo "Best Schhol"
	if (( "$i" == 9 ));
	then
		echo "Hi"
	fi
	(( i++ ))
done
