#!/usr/bin/env bash
# Displays 'Best School' 10 times
# For the 9th iteration, displays 'Best School' and then 'Hi' on a new line.

i=1

while (( i < 10 ))
do
	if (( i == 9))
	then
		echo "Best School"
	fi
	echo "Hi"
	(( i++))
done
