#!/usr/bin/env bash
# Script that displays numbers from 1 to 20 
# Displays '4' and then 'bad luck from China' for the 4th loop iteration
# Displays '9' and then 'bad luck from Japan' for the 9th loop iteration
# Displays '17' and then 'bad luck from Italy' for the 17th loop iteration

i=1

while (( i <= 20 ))
do
	case $(( i )) in
		echo "$i"
		ecg
