#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with, localhost resolves to 127.0.0.2, Facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.tmp
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.tmp
sed -i "2i8.8.8.8 facebook.com"  ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
